export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  ASSET_CLASSES: "/asset-classes",
  EXCHANGES_CLEARING: "/exchanges-clearing",
  FIXED_INCOME: "/fixed-income",
  SUSTAINABLE_FINANCE: "/sustainable-finance",
  MORTGAGE_TECHNOLOGY: "/mortgage-technology",
  INSIGHTS: "/insights",
  DASHBOARD: "/dashboard",
  STAKING: "/staking",
  STAKE: "/stake",
  LOGIN: "/login",
  SIGNUP: "/signup",
  DEPOSIT_PROTECTION: "/deposit-protection",
  DEPOSIT_WITHDRAWAL: "/deposit-withdrawal",
  CONTACT:"/contact",
  SUSCRIBE:"/suscribe",
};
